name: Tests Workflow
on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FULL_NAME: "Ситникова Дарья Константиновна"
      GROUP_NUMBER: "M3116"
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print information
        run: |
          echo "ФИО: ${{ env.FULL_NAME }}"
          echo "Номер группы: ${{ env.GROUP_NUMBER }}"
          echo "Ник на Github: ${{ github.actor }}"

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Run unit tests
        run: python -m unittest discover -s tests

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 --ignore=E501,E302 .
